kind: Deployment
apiVersion: apps/v1
metadata:
  name: "app"

spec:
  replicas: 1
  revisionHistoryLimit: 0

  template:
    spec:
      containers:
        - name: "app"
          image: "app"
          imagePullPolicy: "IfNotPresent"

          ports:
            - name: "app"
              containerPort: "<<REPLACE>>"

      imagePullSecrets:
        - name: "dockerhub-tlake-read-only"

---

apiVersion: v1
kind: Service
metadata:
  name: "app"

spec:
  ports:
    - name: "http-traffic"
      port: 80
      targetPort: "app"

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "app-http"

spec:
  entryPoints:
    - web

  routes:
    - match: "<<REPLACE>>"
      kind: Rule
      services:
        - name: "<<REPLACE>>"
          port: "http-traffic"

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    routeType: "https"
  name: "app-https"

spec:
  entryPoints:
    - websecure

  routes:
    - match: "<<REPLACE>>"
      kind: Rule
      services:
        - name: "<<REPLACE>>"
          port: "http-traffic"

  tls:
    certResolver: "<<REPLACE>>"

