apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml

  # Uncomment this after Traefik is installed and configured with its CRDs.
  # This will create the IngressRoute that allows Traefik to route requests
  # to the argocd-server pod.
  #- traefik-ingress.yaml

patches:
  - path: patch-expose-service.yaml
    target:
      kind: Service
      name: argocd-server

  - path: patch-argocd-server-insecure.yaml
    target:
      kind: Deployment
      name: argocd-server

  - path: patch-argocd-dex-server-insecure.yaml
    target:
      kind: Deployment
      name: argocd-dex-server

  - path: patch-argocd-repo-server-insecure.yaml
    target:
      kind: Deployment
      name: argocd-repo-server

