apiVersion: v1
kind: Deployment
metadata:
  name: argocd-dex-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: dex
          env:
            - name: ARGOCD_DEX_SERVER_DISABLE_TLS
              value: "true"
              valueFrom:
                $patch: delete
                configMapKeyRef:
                  key: dexserver.disable.tls
                  name: argocd-cmd-params-cm
                  optional: true

