kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "traefik"
    service: "traefik-app"
  name: "traefik-app"
  namespace: "traefik"

spec:
  replicas: 1
  revisionHistoryLimit: 0

  selector:
    matchLabels:
      app: "traefik"
      service: "traefik-app"

  template:
    metadata:
      labels:
        app: "traefik"
        service: "traefik-app"
      name: "traefik-app"
      namespace: "traefik"

    spec:
      serviceAccountName: "traefik-service-account"
      containers:
        - name: "app"
          # tag: 3.1.7
          image: "traefik@sha256:74d72c7a1345984f186bddbabcc462b2128d0d8054177dc84afaeac4db1f0f56"
          imagePullPolicy: "IfNotPresent"
          args:
            - "--api.insecure"
            - "--providers.kubernetesingress"

          ports:
            - name: "web"
              containerPort: 80

            - name: "websecure"
              containerPort: 443

            - name: "dashboard"
              containerPort: 8080

          resources:
            requests:
              cpu: "50m"
              memory: "200Mi"

          volumeMounts:
            - name: "certs"
              mountPath: "/etc/certs"

            - name: "dynamic-config"
              mountPath: "/etc/dynamic-config"

            - name: "static-config"
              mountPath: "/etc/traefik"

      imagePullSecrets:
        - name: "dockerhub-tlake-read-only"

      volumes:
        - name: "certs"
          persistentVolumeClaim:
            claimName: "certs"

        - name: "dynamic-config"
          persistentVolumeClaim:
            claimName: "dynamic-config"

        - name: "static-config"
          persistentVolumeClaim:
            claimName: "static-config"

