apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- ingressroute-definitions.yaml
- ingressroute-rbac.yaml
#- ingressroute-resources.yaml
- service-account.yaml
#- daemon-set.yaml
- deployment.yaml
- persistent-volumes.yaml
- service.yaml

namespace: traefik

commonLabels:
  app: traefik
