kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: certs
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dynamic-config
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-config
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

