kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-static-config
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
