apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  loadBalancerIP: 192.168.0.212
  ports:
    - port: 80
      targetPort: dashboard
  selector:
    app: traefik
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  loadBalancerIP: 192.168.0.211
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: websecure
      port: 443
      targetPort: websecure
  selector:
    app: traefik
  type: LoadBalancer

