apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "postgres-data"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Mi"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-longhorn
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: longhorn
