- name: Enable microk8s observability addon
  become: true
  shell: /snap/bin/microk8s enable observability
  run_once: true
  delegate_to: thicket0

- name: Enable microk8s metallb addon
  become: true
  shell: /snap/bin/microk8s enable metallb:192.168.0.210-192.168.0.225
  run_once: true
  delegate_to: thicket0
