kind: Deployment
apiVersion: apps/v1
metadata:
  name: actualbudget
  labels:
    app: actualbudget

spec:
  replicas: 1
  selector:
    matchLabels:
      app: actualbudget
  template:
    metadata:
      labels:
        app: actualbudget
    spec:
      containers:
        - name: actualbudget
          env:
            - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB: 200
            - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB: 500
            - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB: 20
          image: "docker.io/actualbudget/actual-server:24.8.0"
          ports:
            - name: web
              containerPort: 5006
