kind: Deployment
apiVersion: apps/v1
metadata:
  name: "actualbudget"
  labels:
    app: "actualbudget"

spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "actualbudget"
  template:
    metadata:
      labels:
        app: "actualbudget"
    spec:
      containers:
        - name: "actualbudget"
          env:
            - name: "ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB"
              value: "200"
            - name: "ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB"
              value: "500"
            - name: "ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB"
              value: "20"
          image: "docker.io/actualbudget/actual-server:24.8.0"
          ports:
            - name: "app"
              containerPort: 5006
          volumeMounts:
            - name: "data"
              mountPath: "/data"

        - name: "rsync"
          env:
            - name: "RSYNC_CRONTAB"
              value: "crontab"
            - name: "TZ"
              value: "America/Los_Angeles"
          image: "ogivuk/rsync:latest"
          volumeMounts:
            - name: "backup"
              mountPath: "/data/destination"
            - name: "data"
              mountPath: "/data/source"
              readOnly: true
            - name: "rsync"
              mountPath: "/rsync"

      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: "data"

        - name: "backup"
          persistentVolumeClaim:
            claimName: "backup"

        - name: "rsync"
          persistentVolumeClaim:
            claimName: "rsync"

