kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "data"
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: "10Mi"

