kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  #name: "data"
  #name: "data-k8s"
  name: "data-nfs"
spec:
  #storageClassName: "microk8s-hostpath"
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: "10Mi"

