apiVersion: v1
kind: Service
metadata:
  name: "actualbudget"

spec:
  ports:
    - name: "http-traffic"
      port: 80
      targetPort: "app"

  selector:
    app: "actualbudget"

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: "actualbudget-web"
  namespace: "actualbudget"

spec:
  entryPoints:
    - web

  routes:
    - match: "Host(`actual.tlake.io`) || Host(`actualbudget.tlake.io`)"
      kind: Rule
      services:
        - name: "actualbudget"
          port: "http-traffic"

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: "actualbudget-websecure"
  namespace: "actualbudget"

spec:
  entryPoints:
    - websecure

  routes:
    - match: "Host(`actual.tlake.io`) || Host(`actualbudget.tlake.io`)"
      kind: Rule
      services:
        - name: "actualbudget"
          port: "http-traffic"

  tls:
    certResolver: "staging"

