apiVersion: v1
kind: Service
metadata:
  name: actualbudget

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: actualbudget

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: actualbudget-ingress
  namespace: actualbudget

spec:
  entryPoints:
    - web
    - websecure

  routes:
    - match: Host(`actualbudget.tlake.io`)
      kind: Rule
      services:
        - name: actualbudget
          port: web

  tls:
    certResolver: staging
