kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: "actualbudget"
    service: "actualbudget-rsync"
  name: "actualbudget-rsync-crontab"
  namespace: "actualbudget"

data:
  crontab: |
    50 * * * * rsync -avzh /data/source/* /data/destination/

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "actualbudget"
    service: "actualbudget-rsync"
  name: "actualbudget-rsync"
  namespace: "actualbudget"

spec:
  replicas: 1
  revisionHistoryLimit: 0

  selector:
    matchLabels:
      app: "actualbudget"
      service: "actualbudget-rsync"

  template:
    metadata:
      labels:
        app: "actualbudget"
        service: "actualbudget-rsync"
      name: "actualbudget-rsync"
      namespace: "actualbudget"
    spec:
      containers:
        - name: "rsync"
          # version 0.2
          image: "ogivuk/rsync@sha256:75c0cf3b120c644bf6e59b4bcbb5dbce8fce4ff4b43f4aaac3b55434acd90e5a"
          imagePullPolicy: "IfNotPresent"

          env:
            - name: "RSYNC_CRONTAB"
              value: "crontab"

            - name: "TZ"
              value: "America/Los_Angeles"

          resources:
            requests:
              cpu: "1m"
              memory: "3Mi"

          volumeMounts:
            - name: "backup"
              mountPath: "/data/destination"

            - name: "crontab"
              mountPath: "/rsync/crontab"
              subPath: "crontab"

            - name: "data"
              mountPath: "/data/source"
              readOnly: true

      imagePullSecrets:
        - name: "dockerhub-tlake-read-only"

      volumes:
        - name: "crontab"
          configMap:
            name: "actualbudget-rsync-crontab"

        - name: "data"
          persistentVolumeClaim:
            claimName: "data"

        - name: "backup"
          persistentVolumeClaim:
            claimName: "backup"

