kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "container-cache"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2Gi"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "data"
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "20Gi"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "backup"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "20Gi"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "rsync"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: "2Mi"

