kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "CHANGE_VOLUME_NAME"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Mi"

