kind: Deployment
apiVersion: apps/v1
metadata:
  name: "calibre"
  labels:
    app: "calibre"

spec:
  replicas: 1
  revisionHistoryLimit: 0

  selector:
    matchLabels:
      app: "calibre"

  template:
    metadata:
      labels:
        app: "calibre"

    spec:
      containers:
        - name: "calibre"
          # version 0.6.21
          image: "linuxserver/calibre-web:sha256:24c78126d2c47a0bad2fb99fc3048e8cc6bb443333fb347594d27f02092204f2"
          imagePullPolicy: "IfNotPresent"

          env:
            - name: "TZ"
              value: "America/Los_Angeles"

            - name: "DOCKER_MODS"
              value: "linuxserver/mods:universal-calibre"

          resources:
            requests:
              cpu: "100m"
              memory: "450Mi"

          ports:
            - name: "app"
              containerPort: 8083

          volumeMounts:
            - name: "library"
              mountPath: "/books"

            - name: "config"
              mountPath: "/config"

        - name: "rsync"
          # version 0.2
          image: "ogivuk/rsync:sha256:ba8282ca451b397eb6a7ca7ecbf3135876737d27bd6bdbd85f17d7047a6d2578"
          imagePullPolicy: "IfNotPresent"

          env:
            - name: "RSYNC_CRONTAB"
              value: "crontab"

            - name: "TZ"
              value: "America/Los_Angeles"

          resources:
            requests:
              cpu: "1m"
              memory: "5Mi"

          volumeMounts:
            - name: "library"
              mountPath: "/data/source/books"
              readOnly: true

            - name: "config"
              mountPath: "/data/source/config"
              readOnly: true

            - name: "backup"
              mountPath: "/data/destination"

            - name: "rsync"
              mountPath: "/rsync"

      imagePullSecrets:
        - name: "dockerhub-tlake-read-only"

      volumes:
        - name: "library"
          persistentVolumeClaim:
            claimName: "library"

        - name: "config"
          persistentVolumeClaim:
            claimName: "config"

        - name: "backup"
          persistentVolumeClaim:
            claimName: "backup"

        - name: "rsync"
          persistentVolumeClaim:
            claimName: "rsync"

