kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "calibre"
    service: "calibre-rsync"
  name: "calibre-rsync"
  namespace: "calibre"

spec:
  replicas: 1
  revisionHistoryLimit: 0

  selector:
    matchLabels:
      app: "calibre"
      service: "calibre-rsync"

  template:
    metadata:
      labels:
        app: "calibre"
        service: "calibre-rsync"
      name: "calibre-rsync"
      namespace: "calibre"

    spec:
      containers:
        - name: "rsync"
          # version 0.2
          image: "ogivuk/rsync@sha256:ba8282ca451b397eb6a7ca7ecbf3135876737d27bd6bdbd85f17d7047a6d2578"
          imagePullPolicy: "IfNotPresent"

          env:
            - name: "RSYNC_CRONTAB"
              value: "crontab"

            - name: "TZ"
              value: "America/Los_Angeles"

          resources:
            requests:
              cpu: "1m"
              memory: "5Mi"

          volumeMounts:
            - name: "library"
              mountPath: "/data/source/books"
              readOnly: true

            - name: "config"
              mountPath: "/data/source/config"
              readOnly: true

            - name: "backup"
              mountPath: "/data/destination"

            - name: "rsync"
              mountPath: "/rsync"

      imagePullSecrets:
        - name: "dockerhub-tlake-read-only"

      volumes:
        - name: "library"
          persistentVolumeClaim:
            claimName: "library"

        - name: "config"
          persistentVolumeClaim:
            claimName: "config"

        - name: "backup"
          persistentVolumeClaim:
            claimName: "backup"

        - name: "rsync"
          persistentVolumeClaim:
            claimName: "rsync"

