kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "miniflux"
    service: "miniflux-app"
  name: "miniflux-app"
  namespace: "miniflux"

spec:
  replicas: 1
  revisionHistoryLimit: 0

  selector:
    matchLabels:
      app: "miniflux"
      service: "miniflux-app"

  template:
    metadata:
      labels:
        app: "miniflux"
        service: "miniflux-app"
      name: "miniflux-app"
      namespace: "miniflux"

    spec:
      containers:
        - name: "miniflux-app"
          # version 2.2.1 arm64
          image: "miniflux/miniflux@sha256:bf4040c25021bcd390a52fcc8c67af8e2e43435cc3179814a05c1b33a9160265"

          env:
            - name: "ADMIN_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "miniflux_admin_password"

            - name: "ADMIN_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "miniflux_admin_user"

            - name: "BASE_URL"
              value: "https://rss.tlake.io"

            - name: "CREATE_ADMIN"
              value: "1"

            - name: "METRICS_COLLECTOR"
              value: "1"

            - name: "POSTGRES_DB"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_db"

            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_password"

            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_user"

            - name: "DATABASE_URL"
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@miniflux-postgres:5432/$(POSTGRES_DB)?sslmode=disable"

            - name: "RUN_MIGRATIONS"
              value: "1"

          ports:
            - name: "app"
              containerPort: 8080

          resources:
            requests:
              cpu: "3m"
              memory: "60Mi"

      imagePullSecrets:
        - name: "dockerhub-tlake-read-only"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "miniflux"
    service: "miniflux-app"
  name: "miniflux-app"
  namespace: "miniflux"

spec:
  ports:
    - name: "http-traffic"
      port: 80
      targetPort: "app"

  selector:
    app: "miniflux"
    service: "miniflux-app"

  type: NodePort

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app: "miniflux"
    service: "miniflux-app"
  name: "miniflux-web"
  namespace: "miniflux"

spec:
  entryPoints:
    - web

  routes:
    - match: Host(`rss.tlake.io`)
      kind: Rule
      services:
        - name: "miniflux-app"
          port: "http-traffic"

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app: "miniflux"
    service: "miniflux-app"
  name: "miniflux-websecure"
  namespace: "miniflux"

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`rss.tlake.io`)
      kind: Rule
      services:
        - name: "miniflux-app"
          port: "http-traffic"

  tls:
    certResolver: "production"

