kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "miniflux"
    service: "miniflux-postgres"
  name: "miniflux-postgres"
  namespace: "miniflux"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: "miniflux"
      service: "miniflux-postgres"
  template:
    metadata:
      labels:
        app: "miniflux"
        service: "miniflux-postgres"
      name: "miniflux-postgres"
      namespace: "miniflux"
    spec:
      containers:
        - name: "miniflux-postgres"
          env:
            - name: "POSTGRES_DB"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_db"

            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_password"

            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_user"

          image: "postgres:17"
          ports:
            - name: "db"
              containerPort: 5432
          volumeMounts:
            - name: "postgres-data"
              mountPath: "/var/lib/postgresql/data"

      volumes:
        - name: "postgres-data"
          persistentVolumeClaim:
            claimName: "postgres-data"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "miniflux"
    service: "miniflux-postgres"
  name: "miniflux-postgres"
  namespace: "miniflux"

spec:
  ports:
    - name: "db"
      port: 5432
      protocol: TCP
      targetPort: "db"

  selector:
    app: "miniflux"
    service: "miniflux-postgres"

  type: NodePort

