kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "postgres-data"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Mi"

