apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: whoami

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: whoami-web
  namespace: whoami

spec:
  entryPoints:
    - web

  routes:
    - match: Host(`whoami.tlake.io`)
      kind: Rule
      services:
        - name: whoami
          port: web

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: whoami-websecure
  namespace: whoami

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`whoami.tlake.io`)
      kind: Rule
      services:
        - name: whoami
          port: web

  tls:
    certResolver: staging

