# Actual Budget Service Template

version: '3'

services:
  actual_server:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.actual.entrypoints: "web, websecure"
        traefik.http.routers.actual.rule: "Host(`actual.tlake.io`)"
        traefik.http.routers.actual.tls: "true"
        traefik.http.routers.actual.tls.certresolver: "production"
        traefik.http.services.actual.loadbalancer.server.port: 5006
      mode: "replicated"
      replicas: 1
      restart_policy:
        condition: "any"
      placement:
        constraints:
          - "node.platform.arch == armv7l"
    image: "docker.io/actualbudget/actual-server:24.2.0"
    ports:
      # This line makes Actual available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      - '5006:5006'
    environment:
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=200
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=500
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=200
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    networks:
      - "home"
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - "data:/data"

networks:
  # This assumes that the "home" network is an already-existing
  # user-defined overlay network that Traefik routes across.
  home:
    external:
      name: "home"

volumes:
  data:
