# Docker Registry Service Template

version: "3"

services:
  app:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.docker_registry.entrypoints: "web, websecure"
        traefik.http.routers.docker_registry.rule: "Host(`docker-registry.tlake.io`)"
        traefik.http.routers.docker_registry.tls: "true"
        traefik.http.routers.docker_registry.tls.certresolver: "production"
        traefik.http.services.docker_registry.loadbalancer.server.port: 5000
      mode: "replicated"
      replicas: 1
      restart_policy:
        condition: "any"
      placement:
        constraints:
          - "node.platform.arch == aarch64"
    image: "docker.io/registry:2.8.3"
    networks:
      - "home"
    volumes:
      - "app_auth:/var/lib/htpasswd"
      - "app_data:/var/lib/registry"

networks:
  home:
    external:
      name: "home"

volumes:
  app_auth:
  app_data:
