kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "nextcloud"
    service: "nextcloud-app"
  name: "nextcloud-app"
  namespace: "nextcloud"

spec:
  replicas: 1
  revisionHistoryLimit: 0

  selector:
    matchLabels:
      app: "nextcloud"
      service: "nextcloud-app"

  template:
    metadata:
      labels:
        app: "nextcloud"
        service: "nextcloud-app"
      name: "nextcloud-app"
      namespace: "nextcloud"

    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/hostname"
                  operator: In
                  values:
                    - "thicket3"
      containers:
        - name: "app"
          # UPDATE IN cron.yaml AS WELL:
          # tag 29.0.13-fpm-alpine
          image: "nextcloud@sha256:809ce152986caebc1abf1449a4e1d067bdb54fe2728c6b050471f22d31d3186b"
          imagePullPolicy: "IfNotPresent"

          env:
            - name: "NEXTCLOUD_TRUSTED_DOMAINS"
              value: "cloud.tlake.io mansionsyrup:10100 *.ngrok.io 192.168.0.120"

            - name: "OVERWRITEHOST"
              value: "cloud.tlake.io"

            - name: "OVERWRITEPROTOCOL"
              value: "https"

            - name: "OVERWRITECLIURL"
              value: "https://cloud.tlake.io"

            - name: "OVERWRITEWEBROOT"
              value: "/"

            - name: "POSTGRES_DB"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_db"

            - name: "POSTGRES_HOST"
              value: "nextcloud-postgres"

            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_password"

            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_user"

            - name: "REDIS_HOST"
              value: "nextcloud-redis"

            - name: "TRUSTED_PROXIES"
              value: "192.168.0.208/29"

            - name: "TZ"
              value: "America/Los_Angeles"

          ports:
            - name: "fpm"
              containerPort: 9000
              protocol: "TCP"

          resources:
            requests:
              cpu: "100m"
              memory: "900Mi"

          volumeMounts:
            - mountPath: "/var/www/html"
              name: "nextcloud-storage"

            - mountPath: "/var/www/html/data"
              name: "nextcloud-data"

      imagePullSecrets:
        - name: "dockerhub-tlake-read-only"

      volumes:
        - name: "nextcloud-storage"
          persistentVolumeClaim:
            claimName: "nextcloud-storage"

        - name: "nextcloud-data"
          persistentVolumeClaim:
            claimName: "nextcloud-data"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "nextcloud"
    service: "nextcloud-app"
  name: "nextcloud-app"
  namespace: "nextcloud"

spec:
  ports:
    - name: "fpm"
      port: 9000
      targetPort: "fpm"

  selector:
    app: "nextcloud"
    service: "nextcloud-app"

  type: NodePort

