kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "nextcloud"
    service: "nextcloud-postgres"
  name: "nextcloud-postgres"
  namespace: "nextcloud"

spec:
  replicas: 1
  revisionHistoryLimit: 0

  selector:
    matchLabels:
      app: "nextcloud"
      service: "nextcloud-postgres"

  template:
    metadata:
      labels:
        app: "nextcloud"
        service: "nextcloud-postgres"
      name: "nextcloud-postgres"
      namespace: "nextcloud"

    spec:
      containers:
        - name: "postgres"
          # tag v16.8-bullseye
          image: "postgres@sha256:9766852189231700b0f829b80cec1f254e2e7298f211f0446791d258836c82f2"
          imagePullPolicy: "IfNotPresent"

          env:
            - name: "POSTGRES_DB"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_db"

            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_password"

            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_user"

            - name: "TZ"
              value: "America/Los_Angeles"

          ports:
            - name: "db"
              containerPort: 5432

          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"

          volumeMounts:
            - name: "postgres-data"
              mountPath: "/var/lib/postgresql/data"

      imagePullSecrets:
        - name: "dockerhub-tlake-read-only"

      volumes:
        - name: "postgres-data"
          persistentVolumeClaim:
            claimName: "postgres-data"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "nextcloud"
    service: "nextcloud-postgres"
  name: "nextcloud-postgres"
  namespace: "nextcloud"

spec:
  ports:
    - name: "db"
      port: 5432
      protocol: TCP
      targetPort: "db"

  selector:
    app: "nextcloud"
    service: "nextcloud-postgres"

  type: NodePort

