apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- app.yaml
- db.yaml
- persistent-volumes.yaml
- proxy.yaml
- redis.yaml
- rsync.yaml
- transfer.yaml

namespace: "nextcloud"

commonLabels:
  app: "nextcloud"
