kind: Deployment
apiVersion: apps/v1
metadata:
  name: "CHANGE_APP_IDENTIFIER"
  labels:
    app: "CHANGE_APP_IDENTIFIER"

spec:
  replicas: 1
  revisionHistoryLimit: 0

  selector:
    matchLabels:
      app: "CHANGE_APP_IDENTIFIER"

  template:
    metadata:
      labels:
        app: "CHANGE_APP_IDENTIFIER"

    spec:
      containers:
        - name: "CHANGE_APP_IDENTIFIER"
          image: "CHANGE_IMAGE_REF"

          env:
            - name: "CHANGE_ENVVAR_NAME"
              value: "CHANGE_ENVVAR_VALUE"

          ports:
            - name: "app"
              containerPort: CHANGE_PORT_NUMBER

          volumeMounts:
            - name: "CHANGE_VOLUME_NAME"
              mountPath: "/CHANGE_MOUNT_PATH"

      volumes:
        - name: "CHANGE_VOLUME_NAME"
          persistentVolumeClaim:
            claimName: "CHANGE_VOLUME_NAME"

