apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- persistent-volumes.yaml
- routing.yaml

namespace: "CHANGE_APP_IDENTIFIER"

commonLabels:
  app: "CHANGE_APP_IDENTIFIER"
