apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "CHANGE_VOLUME_NAME"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Mi"
  storageClassName: "longhorn"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "CHANGE_VOLUME_NAME"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Mi"
  storageClassName: "nfs-client"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "CHANGE_VOLUME_NAME"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Mi"
  storageClassName: "microk8s-hostpath"
