kind: Deployment
apiVersion: apps/v1
metadata:
  name: "vaultwarden"
  labels:
    app: "vaultwarden"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: "vaultwarden"
  template:
    metadata:
      labels:
        app: "vaultwarden"
    spec:
      containers:
        - name: "vaultwarden"
          env:
            - name: "ADMIN_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "admin_token"
            - name: "DEBIAN_FRONTEND"
              value: "noninteractive"
            - name: "LC_ALL"
              value: "C.UTF-8"
            - name: "PATH"
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - name: "ROCKET_ENV"
              value: "staging"
            - name: "ROCKET_PORT"
              value: "80"
            - name: "ROCKET_WORKERS"
              value: "10"
            - name: "SIGNUPS_ALLOWED"
              value: "true"
            - name: "UDEV"
              value: "off"
            - name: "WEBSOCKET_ENABLED"
              value: "true"
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "mysql_password"
            - name: "MYSQL_DATABASE"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "mysql_database"
            - name: "MYSQL_USER"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "mysql_user"
            - name: "DATABASE_URL"
              value: "mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@mariadb/$(MYSQL_DATABASE)"
          image: "vaultwarden/server:latest"
          ports:
            - name: "app"
              containerPort: 80
          volumeMounts:
            - name: "app-data"
              mountPath: "/data"

        - name: "mariadb"
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "mysql_root_password"
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "mysql_password"
            - name: "MYSQL_DATABASE"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "mysql_database"
            - name: "MYSQL_USER"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "mysql_user"
          image: "mariadb:latest"
          ports:
            - name: "db"
              containerPort: 3306
          volumeMounts:
            - name: "mariadb-data"
              mountPath: "/var/lib/mysql"

      volumes:
        - name: "app-data"
          persistentVolumeClaim:
            claimName: "app-data"
        - name: "mariadb-data"
          persistentVolumeClaim:
            claimName: "mariadb-data"

