kind: Deployment
apiVersion: apps/v1
metadata:
  name: "vaultwarden"
  labels:
    app: "vaultwarden"

spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "vaultwarden"
  template:
    metadata:
      labels:
        app: "vaultwarden"
    spec:
      containers:
        - name: "vaultwarden"
          env:
            - name: "ADMIN_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "admin_token"
            - name: "DEBIAN_FRONTEND"
              value: "noninteractive"
            - name: "LC_ALL"
              value: "C.UTF-8"
            - name: "PATH"
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - name: "ROCKET_ENV"
              value: "staging"
            - name: "ROCKET_PORT"
              value: "80"
            - name: "ROCKET_WORKERS"
              value: "10"
            - name: "SIGNUPS_ALLOWED"
              value: "true"
            - name: "UDEV"
              value: "off"
            - name: "WEBSOCKET_ENABLED"
              value: "true"
            - name: "POSTGRES_DB"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_db"
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_password"
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_user"
            - name: "DATABASE_URL"
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
          image: "vaultwarden/server:1.32.2"
          ports:
            - name: "app"
              containerPort: 80
          volumeMounts:
            - name: "app-data"
              mountPath: "/data"

        - name: "postgres"
          env:
            - name: "POSTGRES_DB"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_db"
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_password"
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: "config"
                  key: "postgres_user"
          image: "postgres:16"
          ports:
            - name: "db"
              containerPort: 5432
          volumeMounts:
            - name: "postgres-data"
              mountPath: "/var/lib/postgresql/data"

      volumes:
        - name: "app-data"
          persistentVolumeClaim:
            claimName: "app-data"
        - name: "postgres-data"
          persistentVolumeClaim:
            claimName: "postgres-data"

