kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "app-data"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Mi"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "mariadb-data"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Mi"

